jenkins:
  systemMessage: |
    Jenkins do projeto Aluga_Ai (provisionado via Configuration as Code).
    Este Jenkins é reproduzível em qualquer máquina.
  numExecutors: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID:-admin}
          password: ${JENKINS_ADMIN_PASSWORD:-admin123}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
unclassified:
  location:
    url: http://localhost:8080/
  shell:
    shell: "/bin/bash"
jobs:
  - script: |
      // Cria um Pipeline que usa o código montado em /workspace (sem checkout git)
      pipelineJob('Aluga_Ai_Pipeline') {
        description('Pipeline do projeto Aluga_Ai rodando sobre o diretório montado /workspace')
        definition {
          cps {
            script('''
              pipeline {
                agent any
                options { timestamps() }
                stages {
                  stage('Preparar workspace') {
                    steps {
                      echo 'Usando código local montado em /workspace'
                      dir('/workspace') {
                        sh 'ls -la'
                      }
                    }
                  }
                  stage('Instalar dependências') {
                    steps {
                      dir('/workspace') {
                        sh 'python3 -m pip install --upgrade pip'
                        sh 'pip3 install -r requirements.txt || true'
                      }
                    }
                  }
                  stage('Testes') {
                    steps {
                      dir('/workspace') {
                        sh 'pytest -q || true'
                      }
                    }
                  }
                }
              }
            '''.stripIndent())
            sandbox(true)
          }
        }
      }
      
      // Para usar Jenkinsfile do repositório Git em vez de /workspace, crie outro job DSL com cpsScm apontando para sua URL.
