jenkins:
  systemMessage: |
    Jenkins do projeto Aluga_Ai (provisionado via Configuration as Code).
    Multibranch Pipeline configurado via Job DSL.
    Integração com Docker e GitHub.
  numExecutors: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID:-admin}
        - password: ${JENKINS_ADMIN_PASSWORD:-admin123}
    mailer:
      smtpHost: "smtp.gmail.com"
      smtpPort: 465
      useSsl: true
      useTls: false
      smtpAuthUsername: "alvaroscareli@gmail.com"
      smtpAuthPassword: "${SMTP_PASSWORD}"
      charset: "UTF-8"
    shell: "/bin/bash"
credentials:
  system:
    domainCredentials:
      - domain:
          name: ""
          description: "Global domain"
          specifications: []
        credentials:
          - usernamePassword:
              scope: SYSTEM
              id: "dockerhub-credentials"
              username: "${DOCKERHUB_USER}"
              password: "${DOCKERHUB_PASSWORD}"
              description: "Credenciais DockerHub (injetadas por env)"
          - usernamePassword:
              scope: SYSTEM
              id: "git-credentials"
              username: "${GIT_USER}"
              password: "${GIT_PASSWORD}"
              description: "Credenciais Git (se privado). Deixe vazio se público."
                - usernamePassword:
                  scope: SYSTEM
                  id: "smpt-gmail"
                  username: "alvaroscareli@gmail.com"
                  password: "${SMTP_PASSWORD}"
                  description: "Credencial SMTP Gmail para notificações."
jobs:
  - script: |
      // Multibranch Pipeline para o repositório remoto
      multibranchPipelineJob('Aluga_Ai_Multibranch') {
        displayName('Aluga_Ai Multibranch')
        description('Pipeline Multibranch do projeto Aluga_Ai usando Jenkinsfile do repositório Git.')
        branchSources {
          branchSource {
            source {
              git {
                id('aluga-ai-git')
                remote('${GIT_REPO_URL}')
                credentialsId('${GIT_CREDENTIALS_ID:-git-credentials}')
                includes('*')
                excludes('')
              }
            }
            strategy {
              defaultBranchPropertyStrategy {
                props {}
              }
            }
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          periodic(1) // scan a cada ~1 minuto
        }
      }
