jenkins:
  systemMessage: |
    Jenkins do projeto Aluga_Ai (provisionado via Configuration as Code).
    Reproduzível entre máquinas. Multibranch configurado via Job DSL.
  numExecutors: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID:-admin}
          password: ${JENKINS_ADMIN_PASSWORD:-admin123}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
unclassified:
  location:
    url: http://localhost:8080/
  shell:
    shell: "/bin/bash"
credentials:
  system:
    domainCredentials:
      - domain:
          name: ""
          description: "Global domain"
          specifications: []
        credentials:
          - usernamePassword:
              scope: SYSTEM
              id: "dockerhub-credentials"
              username: "${DOCKERHUB_USER}"
              password: "${DOCKERHUB_PASSWORD}"
              description: "Credenciais DockerHub (injetadas por env)"
          - usernamePassword:
              scope: SYSTEM
              id: "${GIT_CREDENTIALS_ID}"
              username: "${GIT_USER}"
              password: "${GIT_PASSWORD}"
              description: "Credenciais Git (se privado). Deixe vazio se público."
jobs:
  - script: |
      // Job Multibranch para o repositório remoto
      // Usa variáveis de ambiente substituídas pelo JCasC: ${GIT_REPO_URL}
      // Se GIT_CREDENTIALS_ID estiver vazio e repo for público, Jenkins acessa sem credenciais.
      multibranchPipelineJob('Aluga_Ai_Multibranch') {
        displayName('Aluga_Ai Multibranch')
        description('Pipeline Multibranch do projeto Aluga_Ai usando Jenkinsfile do repositório Git.')
        branchSources {
          branchSource {
            source {
              git {
                id('aluga-ai-git')
                remote('${GIT_REPO_URL}')
                credentialsId('${GIT_CREDENTIALS_ID}')
                includes('*')
                excludes('')
              }
            }
            strategy {
              defaultBranchPropertyStrategy {
                props {}
              }
            }
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          periodic(1) // scan a cada ~1 minuto (ajuste conforme necessidade)
        }
      }
      
      // (Opcional) Pipeline simples local usando /workspace pode ser adicionada novamente se necessário.
