# Generated by Django 5.2.7 on 2025-10-09 18:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("studio", "Studio"),
                            ("loft", "Loft"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cidade", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("rua", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=20)),
                ("cep", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "quartos",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "banheiros",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("vagas_garagem", models.PositiveIntegerField(default=0)),
                ("area_m2", models.PositiveIntegerField()),
                ("andar", models.IntegerField(default=0)),
                ("ano_construcao", models.PositiveIntegerField()),
                ("preco_aluguel", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "condominio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "iptu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("descricao", models.TextField()),
                ("comodidades", models.JSONField(default=list)),
                ("regras_casa", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("manutencao", "Em Manutenção"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("mobiliado", models.BooleanField(default=False)),
                ("aceita_pets", models.BooleanField(default=False)),
                ("wifi", models.BooleanField(default=True)),
                (
                    "max_hospedes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("camas", models.PositiveIntegerField()),
                ("tipo_cama", models.CharField(max_length=50)),
                (
                    "politica_cancelamento",
                    models.CharField(default="moderada", max_length=50),
                ),
                ("checkin_hora", models.TimeField(default="14:00")),
                ("checkout_hora", models.TimeField(default="11:00")),
                (
                    "nota_media",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("total_avaliacoes", models.PositiveIntegerField(default=0)),
                ("anfitriao_nome", models.CharField(max_length=100)),
                ("anfitriao_superhost", models.BooleanField(default=False)),
                ("tempo_anuncio_meses", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "anfitriao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imoveis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "Imóveis",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_checkin", models.DateField()),
                ("data_checkout", models.DateField()),
                (
                    "numero_hospedes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("concluida", "Concluída"),
                            ("rejeitada", "Rejeitada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("preco_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "preco_por_noite",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("numero_noites", models.PositiveIntegerField()),
                (
                    "taxa_limpeza",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "taxa_servico",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("motivo_cancelamento", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "hospede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="reservas.imovel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-criado_em"],
                "unique_together": {("imovel", "data_checkin", "data_checkout")},
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "limpeza",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "comunicacao",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "localizacao",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "valor",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="reservas.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
            },
        ),
    ]
