# Generated by Django 4.2.25 on 2025-10-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_host',
            field=models.BooleanField(default=False, verbose_name='É anfitrião'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
    ]
