# Generated by Django 4.2.25 on 2025-10-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado'),
        ),
    ]
