# Generated by Django 4.2.25 on 2025-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_propriedade_city_propriedade_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='imagem',
            field=models.ManyToManyField(blank=True, related_name='propriedades', to='propriedades.propriedadeimagem'),
        ),
    ]
