# Generated by Django 4.2.25 on 2025-10-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0003_propriedade_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriedade',
            name='imagem',
        ),
    ]
