# Generated by Django 5.2.5 on 2025-11-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0004_remove_propriedade_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='comodidades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
