# Generated by Django 5.2.6 on 2025-11-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0005_propriedade_comodidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='area_m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='banheiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='condominio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='iptu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='vagas_garagem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
