# Generated by Django 5.2.6 on 2025-11-21 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0001_initial'),
        ('propriedades', '0006_propriedade_area_m2_propriedade_banheiros_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='personal', max_length=30)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_para_usuario', to='propriedades.propriedade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_persistidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendação de Usuário',
                'verbose_name_plural': 'Recomendações de Usuário',
                'indexes': [models.Index(fields=['user', 'source'], name='favoritos_u_user_id_2c6705_idx'), models.Index(fields=['generated_at'], name='favoritos_u_generat_56d018_idx')],
                'unique_together': {('user', 'propriedade', 'source')},
            },
        ),
    ]
