name: Validação do Sistema de Recomendação

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite execução manual

jobs:
  validate-recommendation-system:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configurar variáveis de ambiente
      run: |
        echo "DJANGO_SETTINGS_MODULE=aluga_ai_web.settings" >> $GITHUB_ENV
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
        
    - name: Executar migrações do banco
      run: |
        python manage.py migrate --noinput
        
    - name: Executar job de validação
      run: |
        python jobs/validate_recommendation_system.py
        
    - name: Upload dos resultados
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: validation-results
        path: validation_results.json
        
    - name: Exibir resultados
      if: always()
      run: |
        if [ -f validation_results.json ]; then
          echo "=== RESULTADOS DA VALIDAÇÃO ==="
          cat validation_results.json
        else
          echo "Arquivo de resultados não encontrado"
        fi
